$(document).ready(function(){
  $("#dk").click(function(){
    $("#myModal").modal('show')
  })
  //Modal
  $("#dong1").click(function(){
    $("#myModal").modal('hide')
  })
  $("#dong2").click(function(){
    $("#myModal").modal('hide')
  })
  $("#dong3").click(function(){
    $("#myModal").modal('hide')
  })
  $("#dong4").click(function(){
    $("#myModal").modal('hide')
  })
  //
  $("#dn").click(function(){
    $("#modalDangNhap").modal('show')
  })
})
